<?php
session_start();
if(isset($_SESSION['logged_in']))
	{
		unset($_SESSION['logged_in']);
		unset($_SESSION['userData']);
		header('Location:https://www.google.com/accounts/Logout?continue=https://appengine.google.com/_ah/logout?continue=http://localhost/Trekbuddy/');
	}
?>